#!/usr/bin/env bash
# setup.sh — Deploy Vega SOC to a Linux host.
# Idempotent: safe to re-run. Uses the invoking user (no hardcoded username).
set -euo pipefail

# Resolve the target user even when run via sudo
SOC_USER="${SUDO_USER:-$(whoami)}"

HERMES_SOC=~/.hermes/soc
SKILLS_SOC=~/.hermes/skills/soc
SYSTEMD_USER=~/.config/systemd/user
VEGA_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Vega SOC Setup (user: $SOC_USER) ==="

# ── 1. Directory structure ────────────────────────────────────────────────────
echo "[1/8] Creating directories..."
mkdir -p "$HERMES_SOC/cases"
mkdir -p "$SKILLS_SOC/orchestrator"
mkdir -p "$SKILLS_SOC/dashboard"
mkdir -p "$SYSTEMD_USER"

# ── 2. Copy agent files ───────────────────────────────────────────────────────
echo "[2/8] Copying agent files..."
cp "$VEGA_DIR/agents/triage.py"       "$SKILLS_SOC/orchestrator/"
cp "$VEGA_DIR/agents/investigator.py" "$SKILLS_SOC/orchestrator/"
cp "$VEGA_DIR/agents/intel.py"        "$SKILLS_SOC/orchestrator/"
cp "$VEGA_DIR/agents/responder.py"    "$SKILLS_SOC/orchestrator/"
cp "$VEGA_DIR/agents/auditor.py"      "$SKILLS_SOC/orchestrator/"
cp "$VEGA_DIR/agents/orchestrator.py" "$SKILLS_SOC/orchestrator/"
chmod +x "$SKILLS_SOC/orchestrator/orchestrator.py"

# ── 3. Copy dashboard + Vega skill ────────────────────────────────────────────
echo "[3/8] Installing dashboard and vega-soc skill..."
cp "$VEGA_DIR/dashboard/soc_dashboard.py" "$SKILLS_SOC/dashboard/"
mkdir -p "$SKILLS_SOC/vega-soc"
cp "$VEGA_DIR/skills/vega-soc/SKILL.md" "$SKILLS_SOC/vega-soc/"

# ── 4. Initialize buffer and state files ─────────────────────────────────────
echo "[4/8] Initialising state files..."
[ -f "$HERMES_SOC/findings_buffer.json" ]    || echo '{"entries":[]}'      > "$HERMES_SOC/findings_buffer.json"
[ -f "$HERMES_SOC/tickets.json" ]            || echo '[]'                  > "$HERMES_SOC/tickets.json"
[ -f "$HERMES_SOC/investigator_state.json" ] || echo '{"last_processed":0}' > "$HERMES_SOC/investigator_state.json"

# ── 5. UFW logging ────────────────────────────────────────────────────────────
echo "[5/8] Enabling UFW logging (requires sudo)..."
sudo ufw logging on || echo "  WARNING: could not enable UFW logging"

# ── 6. NOPASSWD sudo rules ────────────────────────────────────────────────────
echo "[6/8] Configuring sudoers for SOC actions..."
SUDOERS_FILE="/etc/sudoers.d/vega-soc"

# Validate commands exist before adding rules
UFW_PATH=$(which ufw)
PKILL_PATH=$(which pkill)
SYSTEMCTL_PATH=$(which systemctl)
USERMOD_PATH=$(which usermod)

# APPROVED_SERVICES here must match responder.py
SUDOERS_CONTENT="# Vega SOC — NOPASSWD for containment actions
# Generated by setup.sh — do not edit manually
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH status *
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH insert *
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH deny *
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH delete *
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH limit ssh
$SOC_USER ALL=(ALL) NOPASSWD: $UFW_PATH logging *
$SOC_USER ALL=(ALL) NOPASSWD: $PKILL_PATH -9 -t *
$SOC_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_PATH stop apache2
$SOC_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_PATH stop suricata
$SOC_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_PATH stop tor@default
$SOC_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_PATH stop photo-gallery
$SOC_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_PATH stop homelab-dashboard
$SOC_USER ALL=(ALL) NOPASSWD: $USERMOD_PATH -L *
$SOC_USER ALL=(ALL) NOPASSWD: $USERMOD_PATH -U *
"

echo "$SUDOERS_CONTENT" | sudo tee "$SUDOERS_FILE" > /dev/null
sudo chmod 440 "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" && echo "  sudoers OK" || {
    echo "  ERROR: sudoers validation failed — removing $SUDOERS_FILE"
    sudo rm "$SUDOERS_FILE"
    exit 1
}

# ── 7. Systemd user services ──────────────────────────────────────────────────
echo "[7/8] Installing systemd user services..."

# Stop and disable any old single-agent monitor
systemctl --user stop  triage-monitor.service 2>/dev/null || true
systemctl --user disable triage-monitor.service 2>/dev/null || true

cp "$VEGA_DIR/systemd/soc-orchestrator.service" "$SYSTEMD_USER/"
cp "$VEGA_DIR/systemd/soc-dashboard.service"     "$SYSTEMD_USER/"
systemctl --user daemon-reload
systemctl --user enable  soc-orchestrator.service soc-dashboard.service
systemctl --user start   soc-orchestrator.service soc-dashboard.service

# ── 8. Done ───────────────────────────────────────────────────────────────────
echo "[8/8] Verifying..."
echo ""
echo "=== Setup complete ==="
echo ""
systemctl --user status soc-orchestrator.service --no-pager -l | head -5
echo ""
echo "Dashboard:  http://$(hostname -I | awk '{print $1}'):9200"
echo "Logs:       journalctl --user -u soc-orchestrator -f"
echo "Sudo check: sudo -n ufw status"
